all:
  vkontakte:

    enable_fetch: true
    enable_register_routes: true
    enable_add_js: true
    enable_append_get_params: true

    photo_getter_class: sfVkontaktePhotoGetter

## There is no need to use this config below
    api_url: http://api.vkontakte.ru/api.php
    url: http://vkontakte.ru/

    test_mode: false
    format: JSON
    api_version: 2.0

    methods:
      # отправляет уведомление пользователю.
      sendNotification: { fields: [uids, message],  text_fields: [message]}
      # сохраняет строку статуса приложения для последующего вывода в общем списке приложений на странице пользоваетеля.
      saveAppStatus: { fields: [uid, status], text_fields: [status] }

      #возвращает строку статуса приложения, сохранённую при помощи saveAppStatus.
      getAppStatus: { fields: [uid] }
      # возвращает платежный баланс приложения.
      getAppBalance: { fields: [] }

      # возвращает баланс пользователя на счету приложения.
      getBalance: { fields: [uid] }

      # DEPRECATED переводит голоса со счета приложения на счет пользователя. 
#      addVotes: { fields: [uid, votes] }

      # DEPRECATED списывает голоса со счета пользователя на счет приложения.
      withdrawVotes: { fields: [uid, votes] }
#      transferVotes: { fields: [uid_from, uid_to, votes] }

      # возвращает историю транзакций внутри приложения.
      getTransactionsHistory: { fields: [type, uid_from, uid_to, date_from, date_to, limit] }

      # поднимает пользователю рейтинг от имени приложения.
      addRating: { fields: [uid, rate, message], text_fields: [message]}

      # устанавливает счетчик, который выводится пользователю жирным шрифтом в левом меню, если он добавил приложение в левое меню.
      setCounter: { fields: [uid, counter] }

      # возвращает список SMS-уведомлений, отосланных приложением.
      getSMSHistory: { fields: [uid, date_from, date_to, limit] }

      # отправляет SMS-уведомление на телефон пользователя.
      sendSMSNotification: { fields: [uid, message], text_fields: [message] }

      # возвращает тексты SMS, полученные от пользователей приложения.
      getSMS: { fields: [uid, date_from, date_to] }

      # создает языковую фразу для перевода на другие языки.
      setLanguageValue: { fields: [key, value, locale, description] }

      # удаляет языковую фразу.
      deleteLanguageValue: { fields: [key] }

#    profile_fields:
#      first_name:   { type: string }
#      last_name:    { type: string }
#      nickname:     { type: string }
#      sex:          { type: integer }
#      bdate:        { type: string }
#      city:         { type: integer }
#      country:      { type: integer }
#      timezone:     { type: string }
#      photo:        { type: string }
#      photo_medium: { type: string }
#      photo_big:    { type: string }
#      has_mobile:   { type: boolean }
#      rate:         { type: float }
#      home_phone:   { type: string }
#     mobile_phone: { type: string }
#      university:   { type: integer }
#      university_name: { type: string }
#      faculty:      { type: integer }
#      faculty_name: { type: string }
#      graduation:   { type: integer }
#      contacts: {type: none}
#      education: {type: none}
