sfVkontakteUser:
  options:
    symfony:
      form:   false
      filter: false
  actAs: [sfVkontakteApiUser, Timestampable]
  columns:
    settings: integer
    fetched_at: datetime
  relations:
    Friends:
      class: sfVkontakteUser
      local: user_from
      foreign: user_to
      refClass: sfVkontakteFriendship
      equal: true

sfVkontakteFriendship:
  actAs: [Timestampable]
  options:
    symfony:
      form:   false
      filter: false
  columns:
   user_from: { type: integer, primary: true }
   user_to:   { type: integer, primary: true }
